using Voot.CodeGen.Domain.Schema;

namespace Voot.CodeGen.Generation.Emitters;

/// <summary>Shared plumbing for emitters: file headers and the standard using block.</summary>
public abstract class EmitterBase : IEmitter
{
    public abstract string Name { get; }

    public virtual bool AppliesTo(TableModel table, GenerationContext context) => table.HasPrimaryKey;

    public abstract IEnumerable<GeneratedFile> Emit(TableModel table, GenerationContext context);

    /// <summary>
    /// Header for files that are overwritten on every run. The hand-editable partial files
    /// deliberately do not get one, so they read as ordinary source.
    /// </summary>
    protected static void WriteGeneratedHeader(CodeWriter writer, TableModel table)
    {
        writer.Line("//------------------------------------------------------------------------------");
        writer.Line("// <auto-generated>");
        writer.Line($"//     Generated from table {table.QualifiedName}.");
        writer.Line("//     Changes to this file are lost the next time the generator runs.");
        writer.Line("//     Put hand-written code in the matching partial class instead.");
        writer.Line("// </auto-generated>");
        writer.Line("//------------------------------------------------------------------------------");
        writer.Blank();
    }

    /// <summary>Writes a using block, skipping blanks and de-duplicating, then a blank line.</summary>
    protected static void WriteUsings(CodeWriter writer, params string?[] namespaces)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);

        foreach (var ns in namespaces)
        {
            if (!string.IsNullOrWhiteSpace(ns) && seen.Add(ns))
            {
                writer.Line($"using {ns};");
            }
        }

        writer.Blank();
    }

    /// <summary>
    /// Writes an XML doc block. Lines that open their own tag (<c>&lt;returns&gt;</c>,
    /// <c>&lt;remarks&gt;</c>) are emitted as siblings of the summary rather than inside it.
    /// </summary>
    protected static void WriteSummary(CodeWriter writer, params string[] lines)
    {
        var summaryLines = new List<string>();
        var trailingLines = new List<string>();
        var inTrailer = false;

        foreach (var line in lines)
        {
            if (line.StartsWith('<'))
            {
                inTrailer = true;
            }

            (inTrailer ? trailingLines : summaryLines).Add(line);
        }

        writer.Line("/// <summary>");
        foreach (var line in summaryLines)
        {
            writer.Line($"/// {line}");
        }

        writer.Line("/// </summary>");

        foreach (var line in trailingLines)
        {
            writer.Line($"/// {line}");
        }
    }
}
