using Voot.CodeGen.Domain.Schema;
using Voot.CodeGen.Generation.Naming;

namespace Voot.CodeGen.Generation.Emitters;

/// <summary>
/// Port of <c>SP.cst</c>. Emits one T-SQL script per table containing every procedure the
/// generated data access layer calls. Procedure names come from the same
/// <see cref="NameResolver"/> the data access emitter uses, so the constants in the DAL and
/// the procedures created here cannot drift apart.
/// </summary>
public sealed class StoredProcedureEmitter : EmitterBase
{
    public override string Name => "StoredProcedures";

    public override IEnumerable<GeneratedFile> Emit(TableModel table, GenerationContext context)
    {
        var names = context.Names;
        var settings = context.Settings;
        var writer = new CodeWriter("\t");
        var primaryKey = NameResolver.PrimaryKeyColumn(table);

        writer.Line($"-- Procedures for {table.QualifiedName}");
        writer.Line($"-- Generated by Voot CodeGen. Regenerating this file overwrites hand edits.");
        writer.Line("GO");
        writer.Blank();

        if (settings.IncludeInsert)
        {
            WriteInsert(writer, table, context, primaryKey);
        }

        if (settings.IncludeUpdate)
        {
            WriteUpdate(writer, table, context, primaryKey);
        }

        if (settings.IncludeDelete)
        {
            WriteDelete(writer, table, context, primaryKey);
        }

        if (settings.IncludeSelect)
        {
            WriteSelectByKey(writer, table, context, primaryKey);
        }

        if (settings.IncludeSelectAll)
        {
            WriteSelectAll(writer, table, context);
        }

        if (settings.IncludeSelectByForeignKey)
        {
            foreach (var column in ForeignKeyLookupColumns(table, primaryKey))
            {
                WriteSelectByColumn(writer, table, context, column);
            }
        }

        if (settings.IncludeDeleteByForeignKey)
        {
            foreach (var column in ForeignKeyLookupColumns(table, primaryKey))
            {
                WriteDeleteByColumn(writer, table, context, column);
            }
        }

        var isMapping = names.IsMappingTable(table);

        if (!isMapping && settings.IncludeMaxAndRowCount)
        {
            // A maximum only makes sense for a numeric key.
            if (SqlTypeMap.SupportsMaximumKey(primaryKey))
            {
                WriteMax(writer, table, context, primaryKey);
            }

            WriteRowCount(writer, table, context);
        }

        if (!isMapping && settings.IncludeSelectPaged)
        {
            WritePaged(writer, table, context, primaryKey);
        }

        if (!isMapping && settings.IncludeSelectByQuery)
        {
            WriteByQuery(writer, table, context);
        }

        yield return new GeneratedFile
        {
            RelativePath = $"{context.StoredProcedureFolder}/{table.Name}_Procedures.sql",
            Content = writer.ToString(),
            Emitter = Name,
            TableName = table.Name
        };
    }

    private static IEnumerable<ColumnModel> ForeignKeyLookupColumns(TableModel table, ColumnModel primaryKey) =>
        table.ForeignKeyColumns.Where(c => !string.Equals(c.Name, primaryKey.Name, StringComparison.OrdinalIgnoreCase));

    /// <summary>Drop guard, session options and the CREATE PROCEDURE header.</summary>
    private static void WriteProcedureHeader(
        CodeWriter writer, TableModel table, GenerationContext context, string procedureName)
    {
        var owner = $"[{table.Owner}]";

        writer.Line($"/****** Object: StoredProcedure {owner}.[{procedureName}] ******/");

        if (context.Settings.IncludeDropStatements)
        {
            writer.Line(
                $"IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'{owner}.[{procedureName}]') AND type IN (N'P', N'PC'))");
            writer.Line($"\tDROP PROCEDURE {owner}.[{procedureName}]");
            writer.Line("GO");
        }

        writer.Line("SET ANSI_NULLS ON");
        writer.Line("GO");
        writer.Line("SET QUOTED_IDENTIFIER ON");
        writer.Line("GO");
        writer.Line($"CREATE PROCEDURE {owner}.[{procedureName}]");
    }

    private static void WriteProcedureFooter(CodeWriter writer)
    {
        writer.Line("GO");
        writer.Blank();
    }

    /// <summary>Writes a bracketed, comma-separated parameter list.</summary>
    private static void WriteParameterList(CodeWriter writer, IReadOnlyList<string> parameters)
    {
        writer.Line("(");
        for (var i = 0; i < parameters.Count; i++)
        {
            var comma = i < parameters.Count - 1 ? "," : string.Empty;
            writer.Line($"\t{parameters[i]}{comma}");
        }

        writer.Line(")");
    }

    private static string Declare(ColumnModel column, bool output = false) =>
        $"@{column.Name} {SqlTypeMap.SqlParameterType(column)}{(output ? " OUTPUT" : string.Empty)}";

    /// <summary>
    /// Columns written by insert and update: the non-audit columns plus the audit columns,
    /// which the framework's base data access supplies values for.
    /// </summary>
    private static List<ColumnModel> WritableColumns(TableModel table, GenerationContext context) =>
    [
        .. context.Names.GeneratedNonKeyColumns(table).Where(c => !c.IsComputed && !c.IsRowVersion),
        .. context.Names.AuditColumnsOf(table).Where(c => !c.IsComputed && !c.IsRowVersion)
    ];

    /// <summary>The projection used by every SELECT, in the order FillObject expects.</summary>
    private static List<ColumnModel> ProjectionColumns(TableModel table, GenerationContext context) =>
    [
        .. context.Names.OrderedGeneratedColumns(table),
        .. context.Names.AuditColumnsOf(table)
    ];

    private static void WriteSelectList(CodeWriter writer, TableModel table, GenerationContext context)
    {
        var columns = ProjectionColumns(table, context);
        for (var i = 0; i < columns.Count; i++)
        {
            var comma = i < columns.Count - 1 ? "," : string.Empty;
            writer.Line($"\t[{columns[i].Name}]{comma}");
        }
    }

    private static void WriteInsert(CodeWriter writer, TableModel table, GenerationContext context, ColumnModel primaryKey)
    {
        var procedure = context.Names.InsertProcedure(table);
        var writable = WritableColumns(table, context);
        var isIdentity = primaryKey.IsIdentity;

        WriteProcedureHeader(writer, table, context, procedure);

        var parameters = new List<string> { Declare(primaryKey, isIdentity) };
        parameters.AddRange(writable.Select(c => Declare(c)));
        WriteParameterList(writer, parameters);

        writer.Line("AS");
        writer.Line("BEGIN");
        writer.Line("\tSET NOCOUNT ON;");
        writer.Blank();

        var insertColumns = isIdentity ? writable : [primaryKey, .. writable];

        writer.Line($"\tINSERT INTO {table.QualifiedName}");
        writer.Line("\t(");
        for (var i = 0; i < insertColumns.Count; i++)
        {
            var comma = i < insertColumns.Count - 1 ? "," : string.Empty;
            writer.Line($"\t\t[{insertColumns[i].Name}]{comma}");
        }

        writer.Line("\t)");
        writer.Line("\tVALUES");
        writer.Line("\t(");
        for (var i = 0; i < insertColumns.Count; i++)
        {
            var comma = i < insertColumns.Count - 1 ? "," : string.Empty;
            writer.Line($"\t\t@{insertColumns[i].Name}{comma}");
        }

        writer.Line("\t)");
        writer.Blank();
        writer.Line("\tDECLARE @Result int = @@ROWCOUNT;");

        if (isIdentity)
        {
            // SCOPE_IDENTITY avoids picking up an identity inserted by a trigger, which @@IDENTITY does.
            writer.Line($"\tSET @{primaryKey.Name} = SCOPE_IDENTITY();");
        }

        writer.Blank();
        writer.Line("\tRETURN @Result;");
        writer.Line("END");
        WriteProcedureFooter(writer);
    }

    private static void WriteUpdate(CodeWriter writer, TableModel table, GenerationContext context, ColumnModel primaryKey)
    {
        var procedure = context.Names.UpdateProcedure(table);
        var writable = WritableColumns(table, context);

        WriteProcedureHeader(writer, table, context, procedure);

        var parameters = new List<string> { Declare(primaryKey) };
        parameters.AddRange(writable.Select(c => Declare(c)));
        WriteParameterList(writer, parameters);

        writer.Line("AS");
        writer.Line("BEGIN");
        writer.Line("\tSET NOCOUNT ON;");
        writer.Blank();
        writer.Line($"\tUPDATE {table.QualifiedName}");
        writer.Line("\tSET");

        for (var i = 0; i < writable.Count; i++)
        {
            var comma = i < writable.Count - 1 ? "," : string.Empty;
            writer.Line($"\t\t[{writable[i].Name}] = @{writable[i].Name}{comma}");
        }

        writer.Line($"\tWHERE [{primaryKey.Name}] = @{primaryKey.Name};");
        writer.Blank();
        writer.Line("\tRETURN @@ROWCOUNT;");
        writer.Line("END");
        WriteProcedureFooter(writer);
    }

    private static void WriteDelete(CodeWriter writer, TableModel table, GenerationContext context, ColumnModel primaryKey)
    {
        var procedure = context.Names.DeleteProcedure(table);

        WriteProcedureHeader(writer, table, context, procedure);
        WriteParameterList(writer, [Declare(primaryKey)]);
        writer.Line("AS");
        writer.Line("BEGIN");
        writer.Line("\tSET NOCOUNT ON;");
        writer.Blank();
        writer.Line($"\tDELETE FROM {table.QualifiedName}");
        writer.Line($"\tWHERE [{primaryKey.Name}] = @{primaryKey.Name};");
        writer.Blank();
        writer.Line("\tRETURN @@ROWCOUNT;");
        writer.Line("END");
        WriteProcedureFooter(writer);
    }

    private static void WriteSelectByKey(CodeWriter writer, TableModel table, GenerationContext context, ColumnModel primaryKey)
    {
        var procedure = context.Names.SelectByPrimaryKeyProcedure(table);

        WriteProcedureHeader(writer, table, context, procedure);
        WriteParameterList(writer, [Declare(primaryKey)]);
        writer.Line("AS");
        writer.Line("BEGIN");
        writer.Line("\tSET NOCOUNT ON;");
        writer.Blank();
        writer.Line("\tSELECT");
        WriteSelectList(writer, table, context);
        writer.Line($"\tFROM {table.QualifiedName}");
        writer.Line($"\tWHERE [{primaryKey.Name}] = @{primaryKey.Name};");
        writer.Blank();
        writer.Line("\tRETURN @@ROWCOUNT;");
        writer.Line("END");
        WriteProcedureFooter(writer);
    }

    private static void WriteSelectAll(CodeWriter writer, TableModel table, GenerationContext context)
    {
        var procedure = context.Names.SelectAllProcedure(table);
        var orderBy = context.Settings.OrderByExpression;

        WriteProcedureHeader(writer, table, context, procedure);
        writer.Line("AS");
        writer.Line("BEGIN");
        writer.Line("\tSET NOCOUNT ON;");
        writer.Blank();
        writer.Line("\tSELECT");
        WriteSelectList(writer, table, context);
        writer.Line($"\tFROM {table.QualifiedName}");

        if (!string.IsNullOrWhiteSpace(orderBy))
        {
            writer.Line($"\tORDER BY {orderBy}");
        }

        writer.Line("\t;");
        writer.Blank();
        writer.Line("\tRETURN @@ROWCOUNT;");
        writer.Line("END");
        WriteProcedureFooter(writer);
    }

    private static void WriteSelectByColumn(CodeWriter writer, TableModel table, GenerationContext context, ColumnModel column)
    {
        var procedure = context.Names.SelectByForeignKeyProcedure(table, column);

        WriteProcedureHeader(writer, table, context, procedure);
        WriteParameterList(writer, [Declare(column)]);
        writer.Line("AS");
        writer.Line("BEGIN");
        writer.Line("\tSET NOCOUNT ON;");
        writer.Blank();
        writer.Line("\tSELECT");
        WriteSelectList(writer, table, context);
        writer.Line($"\tFROM {table.QualifiedName}");
        writer.Line($"\tWHERE [{column.Name}] = @{column.Name};");
        writer.Blank();
        writer.Line("\tRETURN @@ROWCOUNT;");
        writer.Line("END");
        WriteProcedureFooter(writer);
    }

    private static void WriteDeleteByColumn(CodeWriter writer, TableModel table, GenerationContext context, ColumnModel column)
    {
        var procedure = context.Names.DeleteByForeignKeyProcedure(table, column);

        WriteProcedureHeader(writer, table, context, procedure);
        WriteParameterList(writer, [Declare(column)]);
        writer.Line("AS");
        writer.Line("BEGIN");
        writer.Line("\tSET NOCOUNT ON;");
        writer.Blank();
        writer.Line($"\tDELETE FROM {table.QualifiedName}");
        writer.Line($"\tWHERE [{column.Name}] = @{column.Name};");
        writer.Blank();
        writer.Line("\tRETURN @@ROWCOUNT;");
        writer.Line("END");
        WriteProcedureFooter(writer);
    }

    private static void WriteMax(CodeWriter writer, TableModel table, GenerationContext context, ColumnModel primaryKey)
    {
        var procedure = context.Names.MaxProcedure(table);

        WriteProcedureHeader(writer, table, context, procedure);
        writer.Line("AS");
        writer.Line("BEGIN");
        writer.Line("\tSET NOCOUNT ON;");
        writer.Blank();
        writer.Line($"\tSELECT ISNULL(MAX([{primaryKey.Name}]), 0)");
        writer.Line($"\tFROM {table.QualifiedName};");
        writer.Blank();
        writer.Line("\tRETURN @@ROWCOUNT;");
        writer.Line("END");
        WriteProcedureFooter(writer);
    }

    private static void WriteRowCount(CodeWriter writer, TableModel table, GenerationContext context)
    {
        var procedure = context.Names.RowCountProcedure(table);

        WriteProcedureHeader(writer, table, context, procedure);
        writer.Line("AS");
        writer.Line("BEGIN");
        writer.Line("\tSET NOCOUNT ON;");
        writer.Blank();
        writer.Line($"\tSELECT COUNT(*) FROM {table.QualifiedName};");
        writer.Blank();
        writer.Line("\tRETURN @@ROWCOUNT;");
        writer.Line("END");
        WriteProcedureFooter(writer);
    }

    private static void WritePaged(CodeWriter writer, TableModel table, GenerationContext context, ColumnModel primaryKey)
    {
        var procedure = context.Names.SelectPagedProcedure(table);
        var columns = ProjectionColumns(table, context);
        var columnList = string.Join(", ", columns.Select(c => $"[{c.Name}]"));

        WriteProcedureHeader(writer, table, context, procedure);
        WriteParameterList(writer,
        [
            "@TotalRows int OUTPUT",
            "@PageIndex int",
            "@RowPerPage int",
            "@WhereClause nvarchar(4000)",
            "@SortColumn nvarchar(128)",
            "@SortOrder nvarchar(4)"
        ]);

        writer.Line("AS");
        writer.Line("BEGIN");
        writer.Line("\tSET NOCOUNT ON;");
        writer.Blank();
        writer.Line("\tSET @PageIndex = ISNULL(@PageIndex, 0);");
        writer.Line("\tSET @RowPerPage = ISNULL(NULLIF(@RowPerPage, 0), 25);");
        writer.Line("\tSET @WhereClause = ISNULL(@WhereClause, '');");
        writer.Line("\tSET @SortColumn = ISNULL(@SortColumn, '');");
        writer.Line("\tSET @SortOrder = ISNULL(@SortOrder, '');");
        writer.Blank();
        writer.Line("\t-- @SortColumn is validated against the table's real columns and @SortOrder");
        writer.Line("\t-- against a fixed pair of literals, so neither can inject SQL. @WhereClause");
        writer.Line("\t-- is still a raw fragment: never build it from untrusted input.");
        writer.Line($"\tIF @SortColumn NOT IN (SELECT name FROM sys.columns WHERE object_id = OBJECT_ID(N'{table.QualifiedName}'))");
        writer.Line($"\t\tSET @SortColumn = '{primaryKey.Name}';");
        writer.Blank();
        writer.Line("\tIF UPPER(@SortOrder) <> 'DESC' SET @SortOrder = 'ASC';");
        writer.Blank();
        writer.Line("\tDECLARE @Sql nvarchar(max);");
        writer.Line("\tDECLARE @Where nvarchar(4000) = CASE WHEN LEN(@WhereClause) > 0");
        writer.Line("\t\tTHEN N' WHERE ' + @WhereClause ELSE N'' END;");
        writer.Blank();
        writer.Line($"\tSET @Sql = N'SELECT @Rows = COUNT(*) FROM {table.QualifiedName}' + @Where;");
        writer.Line("\tEXEC sp_executesql @Sql, N'@Rows int OUTPUT', @Rows = @TotalRows OUTPUT;");
        writer.Blank();
        writer.Line($"\tSET @Sql = N'SELECT {columnList}");
        writer.Line($"\t\tFROM {table.QualifiedName}' + @Where + N'");
        writer.Line("\t\tORDER BY [' + @SortColumn + N'] ' + @SortOrder + N'");
        writer.Line("\t\tOFFSET @Skip ROWS FETCH NEXT @Take ROWS ONLY';");
        writer.Blank();
        // sp_executesql takes variables, not expressions, so the offset is computed first.
        writer.Line("\tDECLARE @Skip int = @PageIndex * @RowPerPage;");
        writer.Line("\tEXEC sp_executesql @Sql, N'@Skip int, @Take int', @Skip = @Skip, @Take = @RowPerPage;");
        writer.Blank();
        writer.Line("\tRETURN @@ROWCOUNT;");
        writer.Line("END");
        WriteProcedureFooter(writer);
    }

    private static void WriteByQuery(CodeWriter writer, TableModel table, GenerationContext context)
    {
        var procedure = context.Names.ByQueryProcedure(table);
        var columns = ProjectionColumns(table, context);
        var columnList = string.Join(", ", columns.Select(c => $"[{c.Name}]"));

        WriteProcedureHeader(writer, table, context, procedure);
        WriteParameterList(writer, ["@Query nvarchar(4000)"]);
        writer.Line("AS");
        writer.Line("BEGIN");
        writer.Line("\tSET NOCOUNT ON;");
        writer.Blank();
        writer.Line("\t-- @Query is concatenated into dynamic SQL. It is a trusted-caller feature:");
        writer.Line("\t-- never pass a value derived from end-user input to this procedure.");
        writer.Line("\tDECLARE @Sql nvarchar(max);");
        writer.Line($"\tSET @Sql = N'SELECT {columnList} FROM {table.QualifiedName}'");
        writer.Line("\t\t+ CASE WHEN LEN(ISNULL(@Query, '')) > 0 THEN N' WHERE ' + @Query ELSE N'' END;");
        writer.Blank();
        writer.Line("\tEXEC sp_executesql @Sql;");
        writer.Blank();
        writer.Line("\tRETURN @@ROWCOUNT;");
        writer.Line("END");
        WriteProcedureFooter(writer);
    }
}
